p = pwd + string(filesep);
f = ["@refineGUI"+string(filesep)+"refineGUI",...
    "@initialisePopup"+string(filesep)+"initialisePopup",...
    "@spikesortGUI"+string(filesep)+"spikesortGUI",...
    "@tagManager"+string(filesep)+"tagManager",...
    "@weightDesigner"+string(filesep)+"weightDesigner"];
for ii = 1:length(f)
    unzip(p + f(ii) + ".mlapp",p + f(ii));
end