function [] = switchButtons(app, opt)
initialMenus = [app.InitialiseMenu,...
    app.LoadMenu];

opsMenus = [app.AddspikeMenu,...
app.AutosplitMenu,...
app.AutomergeMenu,...
app.ForceaddMenu,...
app.NextbatchMenu,...
app.PreviousbatchMenu,...
app.MergeMenu,...
app.NewunitMenu,...
app.RefinebatchMenu,...
app.RemovespikeMenu,...
app.SaveMenu,...
app.ScrubthroughunitMenu,...
app.SplitMenu,...
app.UndoMenu,...
app.RedoMenu,...
app.UnitfrequencyMenu];

opsButtons = [app.AddspikeButton,...
app.AutosplitButton,...
app.AutomergeButton,...
app.AutosortButton,...
app.BinarynamecopyButton,...
app.CleanupButton,...
app.DeleteunitButton,...
app.ForceaddButton,...
app.NextbatchButton,...
app.PreviousbatchButton,...
app.GotobatchButton,...
app.MergeButton,...
app.NewunitButton,...
app.RefinebatchButton,...
app.RemovespikeButton,...
app.AutosortbatchButton,...
app.SavenamecopyButton,...
app.AllOverviewButton,...
app.SplitButton,...
app.AutosortButton,...
app.ToggletagButton,...
app.TagmanagementButton,...
app.AutocreateunitsButton];

opsStateButtons = [app.SelectedButton,...
    app.PlottedButton,...
    app.BatchButton];

opsDropDowns = [app.LeftUnitDropDown,...
app.RightUnitDropDown];

multiChanButtons = [app.TMultiButton,...
    app.LMultiButton,...
    app.RMultiButton];

switch opt
    case 'menuOff'
        [initialMenus.Enable] = deal('off');
    case 'menuOn'
        [initialMenus.Enable] = deal('on');
    case 'opsOff'
        [opsMenus.Enable] = deal('off');
        [opsButtons.Enable] = deal('off');
        [opsStateButtons.Enable] = deal('off');
        [opsDropDowns.Enable] = deal('off');
        [app.Metrics.dropDownArr.Enable] = deal('off');
    case 'opsOn'
        [opsMenus.Enable] = deal('on');
        [opsButtons.Enable] = deal('on');
        [opsStateButtons.Enable] = deal('on');
        [opsDropDowns.Enable] = deal('on');
        [app.Metrics.dropDownArr.Enable] = deal('on');
    case 'multiOff'
        [multiChanButtons.Enable] = deal('off');
    case 'multiOn'
        [multiChanButtons.Enable] = deal('on');
end
end